### ISSUE TITLE
Добавить .gitignore 

### ISSUE THREAD

**Issue by SosiskaPish** [referhus/metalamp#1]
Надо в корневой файл проекта добавить файл `.gitignore`
Дабы файлы по типу:
- `.cache`
- `.saas-cache`
- `dist`
- `node_modules`

Не засоряли репозиторий временными файлами,

Можешь использовать эту конфигурацию 

[gitignore.txt](https://github.com/referhus/metalamp/files/7251953/gitignore.txt)

1. Создать файл `.gitignore` в папке `metalamp`
2. Готово, при следующих `git push` эти файлы не полетят в реп

**Comment by referhus** [comment]
хорошо, спасибо!
